### ISSUE TITLE
Build error ld: library not found for -lmysqlclient for architecture x86_64

### ISSUE THREAD

**Issue by devValley** [PerfectlySoft/Perfect-MySQL#12]
After performing prerequisite steps from the readme, still getting a link error
`ld: library not found for -lmysqlclient for architecture x86_64`

I'm using Xcode 8, beta 2, macOS 10.11.5

**Comment by taplin** [comment]
Just to confirm, the steps you refer to include creating a .pc file or symlinking to the existing .pc file in your MySql installation ? If the .pc file is there per instructions, I would double check that it has the same permissions as its neighbors, and verify that the paths point to a valid location.

I have not used beta3 yet based on issues reported with the swift Language version settings conflicting with auto generated project files, but typically the library not found indicates a missing or misconfigured package config file.

Hope that helps.

Tim

**Comment by devValley** [comment]
Sorry, I meant to write beta 2. I have removed `-fno-omit-frame-pointer` from the mysqlclient.pc file after mysql installation. Permissions seem to fine

`lrwxr-xr-x  1 MyUser  wheel   54 Jul 20 15:54 mysqlclient.pc -> ../../Cellar/mysql/5.7.13/lib/pkgconfig/mysqlclient.pc`

**Comment by devValley** [comment]
Ok, It worked somehow after reinstalling `mysql` and re-generating the project with `swift package generate-xcodeproj`.
