### ISSUE TITLE
Compile Swift Module 'PerfectMySQL'  Error!

### ISSUE THREAD

**Issue by izenloading** [PerfectlySoft/Perfect-MySQL#32]
----------------------------

Apple Swift version 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)
Target: x86_64-apple-darwin17.6.0

-------------------------------------------

.build/checkouts/Perfect-MySQL.git-4976130768219902098/Sources/PerfectMySQL/MySQLStmt.swift:503:43: error: use of undeclared type 'my_bool'
                let isNullBuffers: UnsafeMutablePointer<my_bool>

.build/checkouts/Perfect-MySQL.git-4976130768219902098/Sources/PerfectMySQL/MySQLStmt.swift:214:7: error: binary operator '==' cannot be applied to operands of type 'Int' and 'Bool'
                                0 == mysql_stmt_bind_param(ptr, paramBinds) else {

**Comment by BuZheng-work** [comment]
hello, I meet a same problem，what did you resolve it？Thank you

**Comment by onean** [comment]
because Perfect-MySQL support Mysql 5.7.21,you may install 8.0

**Comment by onean** [comment]
@JiMengfei because Perfect-MySQL support Mysql 5.7.21,you may install 8.0

**Comment by zhangxiaoyuheshui** [comment]
hi, if you solve it, can you tell me the solution, thank you.
@onean , should I install Mysql 5.7.21?

**Comment by AmirHossein1372** [comment]
This worked for me: (based on readme of repository)
-> brew uninstall mysql
-> brew install mysql@5.7
-> brew install mysql@5.7 && brew link mysql@5.7 --force
