### ISSUE TITLE
This package needs a release to be usable by SPM

### ISSUE THREAD

**Issue by ejohnsonw** [PerfectlySoft/Perfect-MySQL#4]
No version tag found in (/homes/typewritersystem/users/ejohnson@ngeosone.com/projects/PerfectTodoList/generation/git/PerfectTodoListBackend/PerfectTodoList/Packages/Perfect-MySQL) package. Add a version tag with "git tag" command. Example: "git tag 0.1.0"

**Comment by kjessup** [comment]
Done. Thank you.
