### ISSUE TITLE
warning: dependency 'PerfectMySQL' is not used by any target warning: failed to retrieve search paths with pkg-config; maybe pkg-config is not installed

### ISSUE THREAD

**Issue by yyyzzq** [PerfectlySoft/Perfect-MySQL#45]
let package = Package(
    name: "MyServerProject",
    products: [
        .executable(name: "MyServerProject", targets: ["MyServerProject"])
    ],
    dependencies: [
        .package(url: "https://github.com/PerfectlySoft/Perfect-HTTPServer.git", from: "3.0.0"),
        .package(url: "https://github.com/PerfectlySoft/Perfect-MySQL.git", from: "3.0.0")
    ],
    targets: [
        .target(name: "MyServerProject", dependencies: ["PerfectHTTPServer"])
    ]
)

**Comment by 5566** [comment]
targets: [
		.target(name: "MyServerProject", dependencies: ["PerfectHTTPServer","PerfectMySQL"])
	]
